### ISSUE TITLE
问一些问题（持续请教，叨扰楼主）

### ISSUE THREAD

**Issue by Dheguowei** [WeiLaiR/WLRIoTPlatform#1]
楼主，我在配置咱们的mosquitto时，已经建立了两个账户。但是里面提到的分别设置不同权限怎么实现。高权限跟低权限这种？我在网上看mosquitto是通过topic来控制权限的。windows环境下想问下楼主acfile.example 里面 这两个账户怎么配置？

**Comment by WeiLaiR** [comment]
确实是通过topic来控制的，高权限用户应该分配更大范围的topic，而低权限用户应尽量小，至于Windows环境下的mosquitto配置我并不了解，本人将mosquitto部署在Linux上使用的
